/**
 * 
 */
package healthcare.api.client.hl7.type;

/**
 * @author anees-ur-rehman
 *
 */
public enum HL7PV2SegmentTypes {
	
	PRIOR_PENDIG_LOCATION("PV2.1"), ACCOMODATION_CODE("PV2.2"), ADMIT_REASON("PV2.3"), TRANSFER_REASON("PV2.4"), PATIENT_VALUABLES("PV2.5"),
	PATIENT_VALUABLES_LOCATION("PV2.6"), VISIT_USER_CODE("PV2.7"), EXPECTED_ADMIT_DATE_TIME("PV2.8"), EXPECTED_DISCHARGE_DATE_TIME("PV2.9"),
	EXPTECTED_LENGTH_INPATIENT_STAY("PV2.10"), ACTUAL_LENGTH_INPATIENT_STAY("PV2.11"), VISIT_DESCRIPTION("PV2.12"), REFERRAL_SOURCE_CODE_LIST("PV2.13"),
	PREVIOUS_SERVICE_DATE("PV2.14"), EMPLOYMENT_ILLNESS_RECORD_INDICATOR("PV2.15"), PURGE_STATUS_CODE("PV2.16"), PURGE_STATUS_DATE("PV2.17"),
	SPECIAL_PROGRAM_CODE("PV2.18"), RETENTION_INDICATOR("PV2.19"), EXPECTED_NUMBER_OF_INSURANCE_PLANS("PV2.20"), VISIT_PUBLICITY_CODE("PV2.21"),
	VISIT_PROTECTION_INDICATOR("PV2.22"), CLINIC_ORGANIZATION_NAME_LIST("PV2.23"), PATIENT_STATUS_CODE("PV2.24"), VISIT_PRIORITY_CODE("PV2.25"),
	PREVIOUS_TREATMENT_DATE("PV2.26"), EXPECTED_DISCHARE_DISPOSITION("PV2.27"), SIGNATURE_ON_FILE_DATE("PV2.28"), FIRST_SIMILAR_ILLNESS_DATE("PV2.29"),
	PATIENT_CHARGE_ADJUSTMENT_CODE("PV2.30"), RECURRING_SERVICE_CODE("PV2.31"), BILLING_MEDIA_CODE("PV2.32"), EXECTED_SURGERY_DATE_TIME("PV2.33"),
	MILITARY_PARTNERSHIP_CODE("PV2.34"), MILITARY_NONAVAILABILITY_CODE("PV2.35"), NEWBORN_BABY_INDICATOR("PV2.36"), BABY_DETAINED_INDICATOR("PV2.37");

	private String value;
	
	private HL7PV2SegmentTypes(String value){
		this.value = value;
	}
	
	public String getValue(){
		return this.value;
	}
}
