/**
 * 
 */
package healthcare.api.client.hl7.type;

/**
 * @author anees-ur-rehman
 *
 */
public enum HL7PV1SegmentTypes {

	PATIENT_SET_ID("PV1.1"),PATIENT_CLASS("PV1.2"), ASSIGENED_PATIENT_LOCATION("PV1.3"), ADDMISSION_TYPE("PV1.4"), PREADMIT_NUMBER("PV1.5"),
	PRIOR_PATIENT_LOCATION("PV1.6"), ATTENDING_DOCTOR_LIST("PV1.7"), REFERRING_DOCTOR_LIST("PV1.8"), CONSULTING_DOCTOR_LIST("PV1.9"),
	HOSPITAL_SERVICE("PV1.10"), PATIENT_TEMPORARY_LOCATION("PV1.11"), PREADMIT_TEST_INDICATORS("PV1.12"), READMISSION_INDICATORS("PV1.13"),
	ADMIT_SOURCES("PV1.14"), AMBULATORY_STATUS_LIST("PV1.15"), VIP_INDICATOR("PV1.16"), ADMITTING_DOCTORS_LIST("PV1.17"), PATIENT_TYPE("PV1.18"),
	VISIT_NUMBER("PV1.19"), FINANCIAL_CLASS_LIST("PV1.20"), CHARGE_PRICE_INDICATOR("PV1.21"), COURTESY_CODE("PV1.22"), CREDIT_RATING("PV1.23"),
	CONTRACT_CODE_LIST("PV1.24"), CONTRACT_EFFECTIVE_DATE_LIST("PV1.25"), CONTRACT_AMOUNT_LIST("PV1.26"), CONTRACT_PERIOD_LIST("PV1.27"),
	INTEREST_CODE("PV1.28"), TRANSFER_TO_BAD_DEBIT_CODE("PV1.29"), TRANSFER_TO_BAD_DEBIT_DATE("PV1.30"), BAD_DEBIT_AGENCY_CODE("PV1.31"),
	BAD_DEBIT_TRANSFER_AMOUNT("PV1.32"), BAD_DEBIT_RECOVERY_AMOUNT("PV1.33"), DELETE_ACCOUNT_INDICATOR("PV1.34"), DELETE_ACCOUNT_DATE("PV1.35"),
	DISCHARGE_DISPOSITION("PV1.36"), DISCHARGE_TO_LOCATION("PV1.37"), DIET_TYPE("PV1.38"), SERVIING_FACILITY("PV1.39"), BED_STATUS("PV1.40"),
	ACCOUNT_STATUS("PV1.41"), PENDING_LOCATION("PV1.42"), PRIOR_TEMPORARY_LOCATION("PV1.43"), ADMIT_DATE_TIME("PV1.44"), DISCHARGE_DATE_TIME("PV1.45"),
	CURRENT_PATIENT_BALANCE("PV1.46"), TOTAL_CHARGE("PV1.47"), TOTAL_ADJUSTMENT("PV1.48"), TOTAL_PAYMENTS("PV1.49"), ALTERNATE_VISIT_ID("PV1.50"),
	VISIT_INDICATOR("PV1.51"), OTHER_HEALTHCARE_PROVIDER_LIST("PV1.52");

	
	private String value;
	
	private HL7PV1SegmentTypes(String value){
		this.value = value;
	}
	
	public String getValue(){
		return this.value;
	}
}
